session_name: super
windows:
  - window_name: super
    layout: tiled
    shell_command_before:
      - source /home/kota/super_ws/devel/setup.bash
      - source /home/kota/livox_ros_ws/devel/setup.bash
      - source /home/kota/mid360_ws/devel/setup.bash
    panes:
      - roscore
      - roslaunch --wait acl_sim start_world.launch
      - roslaunch --wait acl_sim perfect_tracker_and_sim.launch x:=0.0 y:=0.0 z:=3.0 yaw:=0.0
      - roslaunch --wait mission_planner click_demo.launch
